### ISSUE TITLE
Link display text not changeable (reverts to page name)

### ISSUE THREAD

**Issue by geochanto** [apostrophecms/apostrophe-rich-text-permalinks#4]
**Steps to reproduce:**

1. create a "pages" link in rich text
2. change "display text"
3. refresh the page

**Expected result:**
Display text should be maintained as set

**Actual result:**
Display text reverts to the name of the page

**Comment by beaulac** [comment]
Did you make sure the "Always display current title" checkbox is unchecked?

This box is [checked by default](https://github.com/apostrophecms/apostrophe-rich-text-permalinks/blob/cfb1aefae9917520bec4805463bf165d5ad64132/public/js/ckeditorPlugins/permalink/plugin.js#L11) when a link is switched to a permalink 'document' type from a different type.

**Comment by geochanto** [comment]
@beaulac I don't remember if that option was there when I created this issue.

I tried to test, but I think CKeditor has changed. It used to have "pages" link type. Now it's "document" type instead and it's not finding the existing pages so that I could link. I have not had time to work or update anything related to Apostrophe for the past couple of months. I'll leave it up to you guys to test and bugfix if the bug is still there ;)

**Comment by bobclewell** [comment]
I just hit this issue, thinking it was a bug also, and I can confirm @beaulac's resolution. Unchecking that box will then allow for the display text to be changed and for that change to stick when you refresh the page. 

That said, there is still a UX/UI issue here. Why have the field to edit the display test available and active, if you _also_ have to uncheck that box for your change to actually appear? It seems like an unnecessary second step that as confused at least 2 people. The quickest fix, I think, would to just change the default of "Always display current title" to unchecked.
